#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 120000

#import "XC10_XCTest_CDStructures.h"
#import "XC10_SharedHeader.h"
#import "XC10_XCTTestSchedulerWorker.h"

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol XCTTestWorker <XCTTestSchedulerWorker>
- (void)fetchDiscoveredTestClasses:(void (^)(NSSet *, NSError *))arg1;
@end

#endif
