#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 120000

#import "XC10__CDStructures.h"
#import "XC10_SharedHeader.h"
#import <Foundation/Foundation.h>

@class XCTAttachment;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol XCTActivity <NSObject>
@property(readonly, copy) NSString *name;
- (void)addAttachment:(XCTAttachment *)arg1;
@end

#endif
