#!/bin/bash

# Required environment:
# MIXBOX_CI_REPORTS_PATH - where to store reports (junit.xml will be stored), e.g. "/tmp/123"
# MIXBOX_CI_DESTINATION - basename of json in `di/destinations` directory, e.g. "iphone_7_ios114.json"

MIXBOX_CI_TEMPORARY_DIRECTORY="/tmp/083D9EF7-033B-43C3-8D35-2273367B6F92"
for include in "$(dirname $0)/../include/"*; do source "$include"; done

installAdditionalDependencies() {
    installLibssh
    installEmcee
}

installLibssh() {    
    brew ls --versions libssh2 > /dev/null || brew install libssh2
}

installEmcee() {
    echo "Installing Emcee..."
    
    avitoRunnerBinaryPath=`ls -1 "$MIXBOX_CI_TEMPORARY_DIRECTORY"/Emcee/.build/x86_64-*/debug/AvitoRunner|head -1` || true
    
    if [ -e "$avitoRunnerBinaryPath" ]
    then
        : # skip
    else
        cd "$MIXBOX_CI_TEMPORARY_DIRECTORY"
            
        git clone https://github.com/avito-tech/Emcee
        cd Emcee
        make generate
        make build
    fi
        
    avitoRunnerBinaryPath=`ls -1 "$MIXBOX_CI_TEMPORARY_DIRECTORY"/Emcee/.build/x86_64-*/debug/AvitoRunner|head -1`
    
    [ -e "$avitoRunnerBinaryPath" ] || fatalError "Failed to install Emcee"
}

testUsingEmcee() {
    local appName=Tests.app
    local testsTarget=XcuiTests
    local runnerAppName=$testsTarget-Runner.app
    local derivedDataPath=`derivedDataPath`

    mkdir -p "$MIXBOX_CI_REPORTS_PATH"

    echo "Running tests"

    cd "$MIXBOX_CI_SCRIPT_DIRECTORY"
    
    local fbxctestUrl="http://artifactory.msk.avito.ru/artifactory/ios-ci/fb/fbxctest/fbxctest_20181120T145305.zip"
    local fbsimctlUrl="http://artifactory.msk.avito.ru/artifactory/ios-ci/fb/fbsimctl/fbsimctl_20181120T145356.zip"
    
    local emceeAction=
    local emceeArgs=()

    local destinationFile="$(destinationFile)"
    local xctestBundle="$derivedDataPath/Build/Products/Debug-iphonesimulator/$testsTarget-Runner.app/PlugIns/$testsTarget.xctest"
    
    if [ -z "$MIXBOX_CI_EMCEE_MACHINES_CONFIG_GETTER" ]
    then
        emceeAction=runTests
        emceeArgs=("${emceeArgs[@]}" "--temp-folder" "$derivedDataPath")
        emceeArgs=("${emceeArgs[@]}" "--number-of-simulators" "2")
        emceeArgs=("${emceeArgs[@]}" "--schedule-strategy" "progressive")
    else
        local emceeMachines="$derivedDataPath/emcee_destinations.json"
        
        $MIXBOX_CI_EMCEE_MACHINES_CONFIG_GETTER > "$emceeMachines"

        local runtimeDump="$derivedDataPath/runtime_dump.json"
        
        "$avitoRunnerBinaryPath" dump \
                        --test-destinations "$destinationFile" \
                        --fbxctest "$fbxctestUrl" \
                        --xctest-bundle "$xctestBundle" \
                        --output "$runtimeDump"
        
        # Make --test-args-file:
        local testArgsFile="$derivedDataPath/test_args_file.json"
        jq -s '{
            entries: [
                {
                    runtimeDumpJson: .[0],
                    destinationsJson: .[1][].testDestination
                } |
                {
                    testToRun: .runtimeDumpJson[] | {c: .className, m: .testMethods[]} | join("/"),
                    testDestination: {
                        deviceType: .destinationsJson.deviceType,
                        runtime: .destinationsJson.iOSVersion
                    },
                    numberOfRetries: 4
                }
            ]
        }' "$runtimeDump" "$destinationFile" > "$testArgsFile";
        
        
        emceeAction=distRunTests
        emceeArgs=("${emceeArgs[@]}" "--destinations" "$emceeMachines")
        emceeArgs=("${emceeArgs[@]}" "--remote-schedule-strategy" "progressive")
        emceeArgs=("${emceeArgs[@]}" "--run-id" `uuidgen`)
        emceeArgs=("${emceeArgs[@]}" "--number-of-simulators" "1")
        emceeArgs=("${emceeArgs[@]}" "--schedule-strategy" "equally_divided")
        emceeArgs=("${emceeArgs[@]}" "--test-args-file" "$testArgsFile")
        
        
    fi
    
    "$avitoRunnerBinaryPath" "$emceeAction" \
    --fbsimctl "$fbsimctlUrl" \
    --fbxctest "$fbxctestUrl" \
    --junit "$MIXBOX_CI_REPORTS_PATH/junit.xml" \
    --trace "$MIXBOX_CI_REPORTS_PATH/trace.combined.json" \
    --environment "$MIXBOX_CI_SCRIPT_DIRECTORY/emcee/environment.json" \
    --test-destinations "$destinationFile" \
    --number-of-retries 3 \
    --schedule-strategy "progressive" \
    --single-test-timeout 1200 \
    --fbxctest-bundle-ready-timeout 600 \
    --fbxctest-crash-check-timeout 600 \
    --fbxctest-fast-timeout 600 \
    --fbxctest-regular-timeout 600 \
    --fbxctest-silence-timeout 600 \
    --fbxctest-slow-timeout 1200 \
    --runner "$derivedDataPath/Build/Products/Debug-iphonesimulator/$testsTarget-Runner.app" \
    --app "$derivedDataPath/Build/Products/Debug-iphonesimulator/$appName" \
    --xctest-bundle "$xctestBundle" \
    "${emceeArgs[@]}"
}

prepareForTesting
installAdditionalDependencies
buildWith_action_scheme_xcodebuildPipeFilter "build-for-testing" "XcuiTests" "xcpretty"
testUsingEmcee
cleanUpAfterTesting
